name: Echo Commit SHA

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo commit SHA
        run: echo "Commit SHA: ${{ github.event.pull_request.head.sha }}"
