name: Echo Commit SHA

on:
  issue_comment:
    types: [created]

jobs:
  echo-sha:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo commit SHA
        run: python main.py
