name: test

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    if: ${{ github.event.issue.pull_request != null && startsWith(github.event.comment.body, 'test.exe') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment Body
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
      
      - name: echo test
        run: |
          echo "$COMMENT_BODY"
